// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gayrvzlqcxsoifjkakat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdheXJ2emxxY3hzb2lmamtha2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDgzMDIsImV4cCI6MjA3Mzg4NDMwMn0.RgJvjzkvqRHQYCkkekiQKadM6UuebGPdVW14JFdxCVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});